// Map coordinates for the Territory Navigator, Election Day Ops Center, and
// Command Center.
//
// IMPORTANT — provenance: state-level coordinates and flagship-LGA-seat
// coordinates are real (well-known reference points — state capitals / LGA
// headquarters). Coordinates for wards and polling units are NOT surveyed
// positions — we don't have a sourced dataset of real ward/PU centroids.
// They are generated by spreading points in a small ring around their real
// parent location, purely so the map has something sensible to render.
// Never present these sub-LGA points as surveyed/official locations — the
// underlying names and INEC codes for the 6 flagship LGAs are real; the pin
// positions for wards/PUs within them are illustrative layout only.

import { seededInt } from "./seed";

export type LatLng = { lat: number; lng: number };

// Approximate state capital coordinates, keyed by the exact state name string
// used in data/states.json (which comes from the naija-state-local-government
// package, including its spelling of "Nassarawa").
export const STATE_CAPITAL_COORDS: Record<string, LatLng> = {
  Abia: { lat: 5.5265, lng: 7.4864 },
  Adamawa: { lat: 9.2035, lng: 12.4954 },
  "Akwa Ibom": { lat: 5.0377, lng: 7.9128 },
  Anambra: { lat: 6.212, lng: 7.069 },
  Bauchi: { lat: 10.3158, lng: 9.8442 },
  Benue: { lat: 7.7322, lng: 8.5391 },
  Borno: { lat: 11.8333, lng: 13.15 },
  Bayelsa: { lat: 4.9247, lng: 6.2642 },
  "Cross River": { lat: 4.9517, lng: 8.322 },
  Delta: { lat: 6.198, lng: 6.736 },
  Ebonyi: { lat: 6.3249, lng: 8.1137 },
  Edo: { lat: 6.335, lng: 5.6037 },
  Ekiti: { lat: 7.6211, lng: 5.221 },
  Enugu: { lat: 6.5244, lng: 7.5186 },
  "Federal Capital Territory": { lat: 9.0765, lng: 7.3986 },
  Gombe: { lat: 10.2897, lng: 11.1673 },
  Imo: { lat: 5.484, lng: 7.0351 },
  Jigawa: { lat: 11.7564, lng: 9.3382 },
  Kebbi: { lat: 12.4539, lng: 4.1975 },
  Kaduna: { lat: 10.5222, lng: 7.4383 },
  Kano: { lat: 12.0022, lng: 8.592 },
  Kogi: { lat: 7.8023, lng: 6.7333 },
  Katsina: { lat: 12.9908, lng: 7.6018 },
  Kwara: { lat: 8.4966, lng: 4.5426 },
  Lagos: { lat: 6.6018, lng: 3.3515 },
  Nassarawa: { lat: 8.4939, lng: 8.5163 },
  Niger: { lat: 9.6139, lng: 6.5569 },
  Ogun: { lat: 7.1475, lng: 3.3619 },
  Ondo: { lat: 7.2508, lng: 5.1958 },
  Osun: { lat: 7.7719, lng: 4.556 },
  Oyo: { lat: 7.3775, lng: 3.947 },
  Plateau: { lat: 9.8965, lng: 8.8583 },
  Rivers: { lat: 4.8156, lng: 7.0498 },
  Sokoto: { lat: 13.0059, lng: 5.2476 },
  Taraba: { lat: 8.8833, lng: 11.3667 },
  Yobe: { lat: 11.748, lng: 11.9608 },
  Zamfara: { lat: 12.1704, lng: 6.6641 },
};

const NIGERIA_CENTER: LatLng = { lat: 9.082, lng: 8.6753 };

export function getStateCoords(stateName: string): LatLng {
  return STATE_CAPITAL_COORDS[stateName] ?? NIGERIA_CENTER;
}

// Spread `index` of `total` points in a ring around a center point.
// Used for LGA-within-state, ward-within-LGA, and PU-within-ward placement
// where we don't have real sub-state coordinates.
export function ringPoint(center: LatLng, index: number, total: number, radiusDeg: number): LatLng {
  if (total <= 1) return center;
  const angle = (2 * Math.PI * index) / total;
  return {
    lat: center.lat + radiusDeg * Math.sin(angle),
    lng: center.lng + radiusDeg * Math.cos(angle),
  };
}

export const RADIUS_LGA_DEG = 0.35; // spread of LGAs around a state capital
export const RADIUS_WARD_DEG = 0.045; // spread of wards around a flagship LGA center
export const RADIUS_PU_DEG = 0.008; // spread of PUs around a ward center

// Approximate seat coordinates for each of the 5 non-Kwara flagship LGAs
// (real, well-known city/LGA-headquarters locations — not surveyed ward/PU
// points).
export const FLAGSHIP_CENTERS: Record<string, LatLng> = {
  "plateau__jos-north": { lat: 9.9285, lng: 8.8921 }, // Jos city
  "adamawa__yola-north": { lat: 9.2064, lng: 12.4823 }, // Yola
  "kano__kano-municipal": { lat: 12.0022, lng: 8.592 }, // Kano city centre
  "anambra__onitsha-south": { lat: 6.145, lng: 6.79 }, // Onitsha
  "rivers__port-harcourt": { lat: 4.8156, lng: 7.0498 }, // Port Harcourt city centre
};

// Approximate LGA-headquarters coordinates for all 16 Kwara State LGAs
// (real, well-known reference points — LGA headquarters towns — not
// surveyed ward/PU centroids, same provenance caveat as FLAGSHIP_CENTERS
// above). Added for the Kwara State PDP demo build.
export const KWARA_LGA_CENTERS: Record<string, LatLng> = {
  "kwara__asa": { lat: 8.6403, lng: 4.5378 }, // Afon
  "kwara__baruten": { lat: 9.6667, lng: 3.5333 }, // Kosubosu
  "kwara__edu": { lat: 8.8508, lng: 5.4131 }, // Lafiagi
  "kwara__ekiti": { lat: 8.12, lng: 5.65 }, // Araromi-Opin
  "kwara__ifelodun": { lat: 8.4167, lng: 4.7833 }, // Share
  "kwara__ilorin-east": { lat: 8.5167, lng: 4.6667 }, // Oke-Oyi
  "kwara__ilorin-south": { lat: 8.4167, lng: 4.5667 }, // Fufu
  "kwara__ilorin-west": { lat: 8.5, lng: 4.55 }, // Oja-Oba (Ilorin metro core)
  "kwara__irepodun": { lat: 8.1333, lng: 5.1 }, // Omu-Aran
  "kwara__isin": { lat: 8.1667, lng: 5.0 }, // Owu-Isin
  "kwara__kaiama": { lat: 9.6053, lng: 3.9077 }, // Kaiama
  "kwara__moro": { lat: 8.9333, lng: 4.7833 }, // Bode Saadu
  "kwara__offa": { lat: 8.15, lng: 4.7167 }, // Offa
  "kwara__oke-ero": { lat: 7.9833, lng: 5.4167 }, // Iloffa
  "kwara__oyun": { lat: 8.2667, lng: 4.8 }, // Ilemona
  "kwara__patigi": { lat: 8.7333, lng: 5.75 }, // Patigi
};

// Operational viewport lock for the Kwara-wide Command Center map — NOT a
// surveyed state boundary polygon (same provenance caveat as the LGA-center
// points above). Derived from the real KWARA_LGA_CENTERS extremes (south:
// Oke-Ero 7.98°N, north: Baruten 9.67°N, west: Baruten 3.53°E, east: Patigi
// 5.75°E) with a small pad on most sides. The west pad is deliberately kept
// tight (+0.15° instead of the usual +0.35°): Kwara's entire western edge is
// the international border with Benin Republic (confirmed via Wikipedia),
// and the un-padded statewide map view was drifting far enough west to show
// Benin's OSM base-map tiles — rendered with French place labels, and
// visually reading as "not Kwara" — exactly the two problems reported after
// the Session 3 review. Locking the map's pan/zoom to this box keeps the
// Command Center framed on Kwara State itself.
export const KWARA_STATE_BOUNDS: [LatLng, LatLng] = [
  { lat: 7.6333, lng: 3.3833 }, // southwest corner
  { lat: 10.0167, lng: 6.1 }, // northeast corner
];

// --- Mobilisation Module: simulated GPS check-in ---
// We have no surveyed per-PU coordinates (see note above), so a real
// device-vs-PU distance check isn't possible offline. Instead we simulate a
// plausible "device GPS reading vs. registered PU location" distance,
// deterministic per agent so a rehearsal run matches the live pitch run.
// <100m reads as verified (typical smartphone GPS accuracy at a real PU
// compound); >=100m is flagged for manual review, same as a real
// geofence-based check-in would behave.
export const GPS_VERIFY_THRESHOLD_M = 100;

export function simulateGpsCheckIn(agentId: string): { distanceM: number; verified: boolean } {
  const distanceM = seededInt(agentId + "-gps", 4, 190);
  return { distanceM, verified: distanceM < GPS_VERIFY_THRESHOLD_M };
}
